[workspace]
resolver = "2"
members = ["lock-ordering", "locked-state"]

[workspace.package]
edition = "2021"
authors = ["Alex Bakon"]
rust-version = "1.75"
repository = "https://github.com/akonradi/lock-ordering"
license = "MIT"
